# ssh-keygen -t ed25519 -N "" -C "hcvst@<hostname>" -f ~/.ssh/<hostname>_host_ed25519
# Derive age public keys for user and host
# cat ~/.ssh/id_ed25519.pub | ssh-to-age
# cat ~/.ssh/<hostname>_host_ed25519.pub | ssh-to-age
keys:
  - &hcvst_user age1re53jflrhfmdd0s3zzae6jd8wzvpxz3p7u4rgcajngdmg8qf95kqlvg4cr
  - &hcvst_host age1cqxpx2mgs4ae5dpgrf62qzf6sxephv2dtaw24el5py7yj9va44qsqky4fd
  - &hcvst_generic age1lk4kt296ypzaztk3e3p5w9r7gav5pu2u00flxl7pjgpn7vjm5gyqde48e3
  - &hcvst_ultkv age1p7hkzkr92kmjl0wm48pjhjd9v329k4x4udmeem8ztpvvqs3vqv8qw029wu

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *hcvst_user
          - *hcvst_host
          - *hcvst_generic
          - *hcvst_ultkv
