# =============================================================================
# default.nix — ASUS E201NA (sunce)
#
# Generated by Claude (Anthropic) — claude-sonnet-4-6
# Date: 2026-03-26
#
# Purpose: Machine-level configuration for the sunce host. Defines what this
# machine is and what it runs — users, desktop, applications, and services.
# Hardware-specific tuning lives in performance.nix. This file should read
# as "what is this machine for" rather than "how is it tuned".
# =============================================================================

{ hostname, config, pkgs, ... }:

{
  # ---------------------------------------------------------------------------
  # Imports
  #
  # hardware-configuration.nix: Auto-generated by nixos-generate-config.
  # Contains filesystem UUIDs, initrd modules, and detected hardware. Do not
  # edit manually — regenerate with nixos-generate-config if hardware changes.
  #
  # performance.nix: Apollo Lake / eMMC specific tuning. Kernel params, zram,
  # power management, VAAPI, and nixos-hardware modules all live there.
  # Keeping it separate means it can be disabled for debugging or reused as a
  # template for similar low-powered hardware.
  #
  # users: Shared user definitions from common/ so user accounts are
  # consistent across all hosts in the flake.
  # ---------------------------------------------------------------------------
  imports = [
    ./hardware-configuration.nix
    ./performance.nix
    ../common/users/kvst.nix
    ../common/users/hcvst.nix
  ];

  # ---------------------------------------------------------------------------
  # Bootloader
  #
  # systemd-boot is a simple UEFI bootloader. Lighter than GRUB and
  # sufficient for a single-OS machine. canTouchEfiVariables allows NixOS to
  # register itself in the UEFI boot order — required for systemd-boot to
  # work correctly on first install.
  # ---------------------------------------------------------------------------
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ---------------------------------------------------------------------------
  # Networking
  #
  # hostname is passed in as a specialArg from the flake, keeping host
  # identity out of the shared config. NetworkManager handles WiFi and
  # wired connections with a GUI — appropriate for a desktop/laptop.
  # useDHCP is left to NetworkManager rather than set globally to avoid
  # the conflict between the two.
  # ---------------------------------------------------------------------------
  networking = {
    hostName = hostname;
    networkmanager.enable = true;
  };

  # ---------------------------------------------------------------------------
  # Locale & Time
  #
  # Africa/Johannesburg is UTC+2 with no daylight saving time.
  # en_ZA.UTF-8 sets the locale to South African English — affects date
  # format, paper size defaults, and currency formatting in applications.
  # ---------------------------------------------------------------------------
  time.timeZone = "Africa/Johannesburg";
  i18n.defaultLocale = "en_ZA.UTF-8";

  # ---------------------------------------------------------------------------
  # Desktop — XFCE + LightDM
  #
  # GNOME has been removed. On 4GB with an N3350, GNOME's compositor
  # (Mutter) consumes ~300MB at idle and the session feels sluggish.
  # XFCE with compositing disabled is significantly more responsive.
  #
  # LightDM replaces GDM. GDM pulls in GNOME dependencies regardless of
  # the active session — LightDM has no such baggage and starts faster.
  #
  # The keymap uses the South African layout (za), which includes ZAR
  # currency symbol and other local characters as AltGr combinations.
  # ---------------------------------------------------------------------------
  services.xserver = {
    enable = true;
    xkb = { layout = "za"; variant = ""; };
    desktopManager.xfce.enable = true;
  };

  services.xserver.displayManager.lightdm.enable = true;
  services.displayManager.defaultSession = "xfce";

  # ---------------------------------------------------------------------------
  # Audio — PipeWire
  #
  # PipeWire replaces PulseAudio as the audio server. It provides a
  # PulseAudio-compatible interface (pulse.enable) so applications built
  # against PulseAudio work without changes. rtkit grants PipeWire
  # real-time scheduling priority for glitch-free audio. support32Bit is
  # disabled — no 32-bit applications are installed on this machine.
  # ---------------------------------------------------------------------------
  security.rtkit.enable = true;
  services.pulseaudio.enable = false;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = false;
    pulse.enable = true;
  };

  # ---------------------------------------------------------------------------
  # Services
  #
  # printing: CUPS print server. Enables local and network printer support.
  # Pulls in Avahi for printer discovery on the local network.
  #
  # tailscale: WireGuard-based mesh VPN. Allows secure access to this
  # machine from other tailscale nodes without port forwarding. The
  # tailscaled daemon handles key exchange and routing automatically.
  #
  # openssh: SSH daemon for remote access and for nixos-rebuild
  # --target-host deployments from a faster build machine.
  # ---------------------------------------------------------------------------
  services.printing.enable = true;
  services.tailscale.enable = true;
  services.openssh.enable = true;

  # ---------------------------------------------------------------------------
  # Firewall
  #
  # NixOS enables the firewall by default. Ports opened here:
  #   22    — SSH
  #   8000  — local development server (ad-hoc use)
  #   53317 — LocalSend (LAN file transfer, TCP + UDP)
  # ---------------------------------------------------------------------------
  networking.firewall.allowedTCPPorts = [ 22 8000 53317 ];
  networking.firewall.allowedUDPPorts = [ 53317 ];

  # ---------------------------------------------------------------------------
  # Packages
  #
  # System-wide packages available to all users. User-specific tooling
  # should go into Home Manager configs under common/users/ instead.
  # ---------------------------------------------------------------------------
  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = with pkgs; [
    brave
    git
    libreoffice
    networkmanagerapplet
    vim
    vlc
    zip
  ];

  # ---------------------------------------------------------------------------
  # State Version
  #
  # Determines the NixOS release from which stateful data defaults are taken
  # (e.g. file locations, database formats). This is NOT the NixOS version
  # being run — it is the version this machine was first installed with.
  # Do not change this value unless you have read the release notes and
  # understand the implications for stateful services on this host.
  # ---------------------------------------------------------------------------
  system.stateVersion = "23.11";
}