# =============================================================================
# performance.nix — ASUS E201NA (Apollo Lake N3350, 4GB DDR3, eMMC storage)
#
# Generated by Claude (Anthropic) — claude-sonnet-4-6
# Date: 2026-03-26
#
# Purpose: Hardware-specific performance and power tuning for a low-powered
# laptop. Separated from default.nix so tweaks can be isolated, disabled,
# or reused as a template for similar hardware.
# =============================================================================

{ config, pkgs, lib, inputs, ... }:

{
  # ---------------------------------------------------------------------------
  # nixos-hardware Modules
  #
  # nixos-hardware is a community repository of NixOS modules that apply
  # hardware-specific tweaks without requiring manual research. We import
  # two generic modules here. Neither has an Apollo Lake specific profile
  # so the coverage is partial — our explicit settings below cover the gaps.
  #
  # common-cpu-intel pulls in two things:
  #   1. cpu-only.nix: sets hardware.cpu.intel.updateMicrocode = true
  #      Intel ships microcode updates that fix CPU bugs, errata, and
  #      occasionally security vulnerabilities post-silicon. Without this,
  #      the CPU runs whatever microcode was flashed at the factory. This
  #      is the one setting from this module we do NOT duplicate ourselves
  #      and the primary reason to import it.
  #   2. common/gpu/intel: sets hardware.opengl.enable = true and exposes
  #      an opt-in option to load i915 at initrd stage 1. We explicitly set
  #      hardware.opengl ourselves below with extraPackages, so this is
  #      redundant but harmless — our value takes precedence.
  #
  # common-pc-laptop pulls in two things:
  #   1. common/pc: sets powerManagement.enable = true
  #      We set this explicitly below — redundant but harmless.
  #   2. services.tlp.enable = lib.mkDefault true (unless power-profiles-daemon
  #      is active). mkDefault loses to any explicit value, so our full TLP
  #      config below takes complete precedence. No conflict.
  #
  # What these modules do NOT cover for this hardware:
  #   - Apollo Lake specific kernel params (we handle this)
  #   - eMMC tuning — noatime, BFQ scheduler, journald limits (we handle this)
  #   - zram configuration (we handle this)
  #   - VAAPI / i965 driver selection (we handle this)
  #   - earlyoom (we handle this)
  #   - Nix build concurrency limits (we handle this)
  #
  # common-pc-laptop-ssd is intentionally excluded. That module enables
  # fstrim — periodic TRIM for SSDs. eMMC manages wear levelling internally
  # via its own controller; running fstrim on eMMC is either a no-op or
  # harmful depending on the controller firmware.
  # ---------------------------------------------------------------------------
  imports = [
    inputs.nixos-hardware.nixosModules.common-cpu-intel
    inputs.nixos-hardware.nixosModules.common-pc-laptop
  ];

  # ---------------------------------------------------------------------------
  # Kernel & Boot Parameters
  #
  # linuxPackages_latest: Tracks the latest mainline kernel. Apollo Lake
  # received driver and power management improvements in kernels after the
  # 23.11 default, so staying current is worthwhile here. If regressions
  # occur (i915 and power management are occasional culprits), pin to a
  # known-good LTS with linuxPackages_6_6 or similar.
  #
  # mitigations=off: Disables kernel patches for Spectre, Meltdown, and
  # related CPU speculative execution vulnerabilities. These patches work by
  # flushing CPU buffers and inserting barriers on every context switch and
  # syscall — on a CPU without silicon-level fixes (N3350 predates them) the
  # overhead is 10-30% on syscall-heavy workloads. Safe to disable on a
  # personal single-user machine. Note: Flatpak apps, containers, or
  # untrusted binaries reintroduce attack surface — if those workloads are
  # added later, reconsider. The N3350 has no hyperthreading (2 cores, 2
  # threads) so nosmt adds nothing here.
  #
  # nowatchdog / nmi_watchdog=0: The hardware watchdog is a timer circuit
  # that reboots the machine if the kernel stops responding — useful on
  # servers, unnecessary on a personal laptop. It generates periodic
  # interrupts that wake the CPU from idle states, increasing power
  # consumption and adding latency noise. Disabling it reduces interrupt
  # overhead and helps C-state transitions work correctly.
  #
  # intel_idle.max_cstate=4: C-states are CPU power-saving sleep levels —
  # C0 is active, C1 is halted, C6/C7 are deep sleep with power gated.
  # Apollo Lake has a known latency spike issue on deep C-state exit, but
  # this has largely been resolved in kernels since ~5.15. Capping at C4
  # rather than C1 allows meaningful idle power savings while avoiding the
  # worst latency outliers. Validate with powertop or turbostat — if
  # stuttering is observed under load, try reducing to max_cstate=2.
  #
  # elevator=bfq: BFQ (Budget Fair Queueing) is an I/O scheduler designed
  # for responsiveness on slow storage. It gives interactive processes
  # priority over background I/O, which dramatically reduces the "system
  # freezes while something is writing" feeling common on eMMC. Much more
  # impactful than CFQ or mq-deadline for desktop workloads on slow storage.
  # ---------------------------------------------------------------------------
  boot.kernelPackages = pkgs.linuxPackages_6_6; # latests not avilable on hydra
  boot.kernelParams = [
    "mitigations=off"          # ~10-15% perf gain on N3350; acceptable on personal hw
    "nowatchdog"               # disable hardware watchdog timer, reduces interrupts
    "nmi_watchdog=0"           # disable NMI (Non-Maskable Interrupt) watchdog
    "intel_idle.max_cstate=4"  # allow deep C-states, avoid C1-only power regression
    "elevator=bfq"             # BFQ I/O scheduler — big responsiveness win on eMMC
  ];

  # ---------------------------------------------------------------------------
  # VM / Memory Pressure Tuning
  #
  # vm.swappiness: Scale of 0-100 controlling how aggressively the kernel
  # moves anonymous memory (process heap/stack) to swap. Default is 60.
  # With zram active, some swapping is desirable — zram swap is fast and
  # compressed, so swapping to it is cheap. Setting too low (e.g. 5)
  # means the kernel holds stale process memory in RAM that could be better
  # used as page cache. 15 is a reasonable balance: prefers RAM but allows
  # zram to absorb pressure before it becomes critical.
  #
  # vm.dirty_ratio / vm.dirty_background_ratio: "Dirty" pages are RAM
  # pages holding data not yet written to disk. dirty_background_ratio (5%)
  # is the threshold at which background writeback starts quietly flushing
  # to disk. dirty_ratio (20%) is the hard ceiling — processes block if
  # dirty pages exceed this. Keeping background ratio low ensures writes
  # happen in small batches rather than large bursts that saturate the eMMC.
  #
  # vm.vfs_cache_pressure: Controls how aggressively the kernel reclaims
  # memory used for directory entry and inode caches. Default 100 means
  # the kernel reclaims VFS cache at the same rate as page cache. Lowering
  # to 50 biases it toward keeping the filesystem metadata cache warm,
  # which reduces repeated directory lookups on slow eMMC storage.
  # ---------------------------------------------------------------------------
  boot.kernel.sysctl = {
    "vm.swappiness" = 15;                # allow some zram swap; 5 was too conservative
    "vm.dirty_ratio" = 20;               # max dirty pages before blocking writes
    "vm.dirty_background_ratio" = 5;     # background writeback threshold
    "vm.vfs_cache_pressure" = 50;        # retain VFS cache longer (default 100)
  };

  # ---------------------------------------------------------------------------
  # eMMC Write Reduction
  #
  # Every file read on a standard Linux mount updates the file's atime
  # (access time) metadata, which requires a write back to the filesystem.
  # On eMMC this matters for two reasons: eMMC has a lower write endurance
  # rating than SSDs (measured in total bytes written over the device
  # lifetime), and the controller handles random small writes poorly.
  # noatime disables atime updates entirely. nodiratime is redundant when
  # noatime is set (noatime implies nodiratime) so it is omitted.
  # ---------------------------------------------------------------------------
  fileSystems."/" = {
    options = [ "noatime" ];
  };

  # ---------------------------------------------------------------------------
  # zram Compressed Swap
  #
  # zram creates a block device backed by a compressed region of RAM.
  # When the kernel needs to swap a memory page, instead of writing it to
  # the slow eMMC it compresses it (using zstd, which is fast and has a
  # good ratio) and stores it in RAM. Effective memory is increased because
  # compressed pages take less space — typical ratios for application memory
  # are 2:1 to 3:1.
  #
  # memoryPercent=50: Reserves ~2GB for compressed swap. Previously 75%
  # (3GB) was specified but this competes with actual workload memory on a
  # 4GB machine. 50% is a better balance unless the workload is heavily
  # browser-tab-heavy, in which case 60-75% may be warranted.
  #
  # priority=100: Ensures the kernel always prefers zram over any physical
  # swap partition. Without this, the kernel may use both at equal priority,
  # resulting in eMMC swap I/O when zram space is still available.
  # The physical swap partition in hardware-configuration.nix can be
  # disabled (swapDevices = []) to prevent eMMC swap entirely.
  # ---------------------------------------------------------------------------
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;
    priority = 100;        # always prefer zram over disk swap
  };

  # ---------------------------------------------------------------------------
  # tmpfs for /tmp
  #
  # Mounts /tmp as a RAM-backed tmpfs instead of writing to eMMC. Build
  # tools, browsers, and many applications write temporary files heavily.
  # Keeping these in RAM avoids eMMC write amplification and is
  # significantly faster for temp-heavy workloads. On 4GB, tmpfs /tmp
  # defaults to 50% of RAM — it only allocates what is actually used,
  # so it does not statically consume 2GB.
  # ---------------------------------------------------------------------------
  boot.tmp.useTmpfs = true;

  # ---------------------------------------------------------------------------
  # Intel GPU / VAAPI Hardware Video Decode
  #
  # The N3350 has an Intel HD 500 GPU (Gen 9 LP, Apollo Lake). VAAPI
  # (Video Acceleration API) exposes the GPU's fixed-function video decode
  # hardware — H.264, HEVC, VP8/VP9. On this CPU, hardware decode via VAAPI
  # is essential: the N3350 struggles to software-decode 1080p H.264 in
  # real time, but hardware decode handles it comfortably.
  #
  # hardware.graphics.enable is also set by the common-cpu-intel module above
  # via common/gpu/intel. Our definition here extends it with extraPackages
  # — NixOS merges the attrsets so both take effect.
  #
  # i965 vs intel-media-driver (iHD): iHD supports Gen 9.5+ (Kaby Lake).
  # i965 supports up to Gen 9 including Apollo Lake. Using iHD here either
  # fails silently or falls back to software — i965 must be forced explicitly.
  #
  # libva-vdpau-driver / libvdpau-va-gl: Route VDPAU calls through VAAPI. 
  # Retained because VLC uses VDPAU by default — removing these would lose 
  # hardware decode in VLC without additional configuration.
  # ---------------------------------------------------------------------------
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-vaapi-driver       # i965 VAAPI backend for Apollo Lake
      libva-vdpau-driver       # VDPAU-over-VAAPI bridge (needed by VLC)
      libvdpau-va-gl           # OpenGL VDPAU backend
    ];
  };

  environment.variables = {
    LIBVA_DRIVER_NAME = "i965";   # force i965 backend (not iHD)
    VDPAU_DRIVER = "va_gl";       # route VDPAU through VAAPI
  };

  # ---------------------------------------------------------------------------
  # Power Management — thermald and TLP
  #
  # powerManagement.enable is also set by common-pc-laptop above via
  # common/pc. Our explicit declaration here is redundant but documents
  # intent clearly — no conflict.
  #
  # thermald: Intel's thermal management daemon. It monitors CPU temperature
  # sensors and applies cooling actions proactively before the hardware hits
  # its thermal limit and forces a hard throttle. On a thin laptop with
  # limited cooling, thermald keeps the CPU in a sustainable operating range
  # rather than oscillating between full speed and emergency throttle.
  #
  # TLP: common-pc-laptop sets services.tlp.enable = mkDefault true. Our
  # full TLP config block below overrides this entirely — mkDefault loses
  # to any explicit value. We keep our own enable = true for clarity.
  #
  # schedutil governor: Sets CPU frequency based on scheduler utilisation
  # data. Reacts faster than ondemand and integrates with the kernel
  # scheduler's own load tracking — better for bursty interactive workloads.
  #
  # CPU_ENERGY_PERF_POLICY_ON_BAT=power: Sets the CPU's Energy Performance
  # Preference (EPP) hint to "power" on battery. This is a hardware-level
  # hint to the CPU's internal frequency/voltage control, separate from the
  # OS governor. Tells the CPU to bias toward efficiency over performance.
  #
  # CPU_MAX_PERF_ON_BAT=60: Caps the CPU at 60% of maximum performance on
  # battery. The N3350 turbos to 2.4GHz but generates heat it can barely
  # dissipate — capping burst reduces heat, fan noise, and battery drain.
  #
  # USB_AUTOSUSPEND=1: Allows USB devices to enter a low-power suspended
  # state when idle. The kernel will resume them automatically on activity.
  # Safe for most peripherals; can cause issues with some USB audio devices
  # or poorly implemented USB hardware.
  #
  # WIFI_PWR_ON_BAT=5: Enables WiFi power saving on battery. Level 5 is
  # the most aggressive setting — the card sleeps between beacon intervals.
  # Can introduce small latency spikes on WiFi; disable if this causes
  # connection instability with your router.
  #
  # PCIE_ASPM powersupersave: Allows PCIe devices (WiFi, storage controller)
  # to enter low-power link states when idle. Most aggressive setting.
  # ---------------------------------------------------------------------------
  powerManagement.enable = true;
  services.thermald.enable = true;

  services.tlp = {
    enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC = "schedutil";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
      CPU_ENERGY_PERF_POLICY_ON_BAT = "power";   # EPP hint to CPU hardware
      CPU_MAX_PERF_ON_BAT = 60;
      USB_AUTOSUSPEND = 1;
      WIFI_PWR_ON_BAT = 5;
      PCIE_ASPM_ON_BAT = "powersupersave";
    };
  };

  # ---------------------------------------------------------------------------
  # earlyoom — Proactive Out-of-Memory Process Termination
  #
  # When Linux runs out of memory it invokes the kernel OOM killer, which
  # selects a process to terminate. The problem is timing: by the time it
  # fires, the system is typically already thrashing — all RAM and swap
  # exhausted, every allocation blocking. On a 4GB machine with a 1.1GHz
  # CPU this manifests as a complete freeze lasting tens of seconds.
  #
  # earlyoom monitors free memory continuously in userspace. When free RAM
  # drops below freeMemThreshold it sends SIGTERM to the process with the
  # highest memory usage, giving it a chance to exit cleanly before
  # escalating to SIGKILL. The result is a single application dying visibly
  # rather than the entire desktop session locking up.
  # ---------------------------------------------------------------------------
  services.earlyoom = {
    enable = true;
    freeMemThreshold = 10;   # slightly more headroom than default
    freeSwapThreshold = 15;
  };

  # ---------------------------------------------------------------------------
  # systemd-journald Log Size Limits
  #
  # By default journald retains logs until disk usage limits are hit, which
  # on a 49GB eMMC partition can accumulate gigabytes over time. More
  # importantly, journald performs frequent small writes as logs are
  # appended — on eMMC this write pattern is expensive. Capping persistent
  # log storage at 100MB and runtime (in-memory) logs at 50MB keeps disk
  # usage bounded and reduces write pressure. Logs older than these limits
  # are automatically rotated out.
  # ---------------------------------------------------------------------------
  services.journald.extraConfig = ''
    SystemMaxUse=100M
    RuntimeMaxUse=50M
  '';

  # ---------------------------------------------------------------------------
  # Nix Build Concurrency Limits
  #
  # By default the Nix daemon runs as many build jobs in parallel as there
  # are CPU cores. On the N3350 with 4GB, a nix build compiling anything
  # non-trivial will spawn multiple compiler processes that collectively
  # exhaust RAM, triggering swap and making the machine unusable.
  #
  # max-jobs=1 ensures only one derivation builds at a time. cores=1 limits
  # each job to a single core. Builds take longer but the machine remains
  # usable. For heavy rebuilds, build on a faster machine and deploy with:
  #   nixos-rebuild switch --target-host user@sunce --build-host localhost
  # ---------------------------------------------------------------------------
  nix.settings = {
    max-jobs = 1;
    cores = 1;
  };
}